# Generated by Django 3.2.5 on 2021-07-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('location', models.CharField(max_length=100)),
                ('Air_temperature', models.FloatField()),
                ('Wind_speed', models.FloatField()),
                ('Gust_speed', models.FloatField()),
                ('Wind_direction', models.FloatField()),
                ('Relative_humidity', models.FloatField()),
                ('Dew_point_temperature', models.FloatField()),
                ('Precipitation_amount', models.FloatField()),
                ('Precipitation_intensity', models.FloatField()),
                ('Snow_depth', models.FloatField()),
                ('Pressure', models.FloatField()),
                ('Horizontal_visibility', models.FloatField()),
                ('Cloud_amount', models.FloatField()),
            ],
        ),
    ]
