# Generated by Django 3.2.5 on 2021-09-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210728_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.CharField(max_length=120)),
                ('plural', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('preptime', models.CharField(max_length=120)),
                ('image_link', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('ingredients', models.CharField(max_length=120)),
                ('instructions', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_size_whole', models.IntegerField()),
                ('package_size_decimal', models.IntegerField()),
                ('category', models.CharField(max_length=120)),
                ('brand_name', models.CharField(max_length=120)),
                ('product_name', models.CharField(max_length=120)),
                ('ean_code', models.CharField(max_length=120)),
                ('price_wholenumber', models.IntegerField()),
                ('price_decimal', models.IntegerField()),
                ('price_unit', models.CharField(max_length=120)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
            ],
        ),
    ]
