# Generated by Django 3.2.5 on 2021-09-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ingredient_product_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='package_size_decimal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_size_whole',
        ),
    ]
